### ISSUE TITLE
Bro 2.5 & E-K 5.1.1

### ISSUE THREAD

**Issue by garanews** [danielguerra69/bro-debian-elasticsearch#10]
Hello,
did you tested with latest version of E-K?

**Comment by danielguerra69** [comment]
Hi,

Tested
I have tested danielguerra/bro-alpine-elasticsearch:x-pack with es 5 with xpack installed
Check
https://github.com/danielguerra69/bro-alpine-elasticsearch/blob/master/docker-compose.yml <https://github.com/danielguerra69/bro-alpine-elasticsearch/blob/master/docker-compose.yml>
The alpine version has no file extraction or pcap integration yet. It has tcprs running. 
I tested it with danielguerra/elasticsearch-x-pack & danielguerra/kibana-x-pack

Not tested.
You could try to run danielguerra/bro-debian-elasticsearch with es5+. Only the kibana config from the docker-compose 
file won’t work. es5+ uses more memory and is hard to run in my test environment. I have tested it with es 2.4. Beside the
config for kibana nothing has changed in es5+ so everything should work.

**Comment by danielguerra69** [comment]
no problem
