### ISSUE TITLE
tcprs

### ISSUE THREAD

**Issue by oflebbe** [danielguerra69/bro-debian-elasticsearch#6]
bro in the forensic container does not work since it still references tcprs. (In bro-extra first line)

**Comment by danielguerra69** [comment]
Sorry for the trouble maybe this repo will help you

docker run -ti danielguerra/bro-debian-elasticsearch:develop /bin/sh

It is rather big but in /tmp are all the sources i used when everything was still working.

**Comment by oflebbe** [comment]
Thanks for hinting at the old sources. I was able to reconstruct the Aug snapshot of the docker images.

**Comment by danielguerra69** [comment]
tcprs is working again
